=== dan2097/opsin/opsin-core/src/main/resources/uk/ac/cam/ch/wwmm/opsin/resources/tokenLists.dtd
<!--Further information is available in XmlDeclarations.java if this is not sufficient-->

<!-- A list of tokens -->
<!ELEMENT tokenLists (tokenList)+>
<!ELEMENT tokenList (token)+>
<!ATTLIST tokenList tagname (alkaneStemComponent|alkaneStemModifier|biochemicalLinkage|bridgeFormingO|carbohydrateRingSize|chargeSpecifier|closebracket|cyclo|fractionalMultiplier|functionalClass|functionalGroup|functionalModifier|fusedRingBridge|group|heteroatom|hydro|hyphen|ine|infix|hydrocarbonFusedRingSystem|multiplier|NA|openbracket|oxidationNumberSpecifier|polyCyclicSpiro|ringAssemblyMultiplier|stereoChemistry|structuralCloseBracket|structuralOpenBracket|subtractivePrefix|suffix|suffixPrefix|unsaturator) #REQUIRED
                    type (acidReplacingFunctionalGroup|acidStem|aminoAcid|anhydro|basic|carbohydrate|carbohydrateConfigurationalPrefix|chain|charge|cisOrTrans|chalcogenAcidStem|dehydro|deoxy|diValentGroup|dlStereochemistry|EorZ|elementaryAtom|endoExoSynAnti|functionalClass|group|heteratomRemoval|inline|monoValentGroup|monoValentStandaloneGroup|nonCarboxylicAcid|ring|RorS|simpleGroup|substituent|root|VonBaeyer) #IMPLIED
                    subType (acetalLike|alkaneStem|amyl|anhydride|apioFuranose|arylSubstituent|biochemical|carbohydrateStemAldose|carbohydrateStemKetose|carbonylReplacement|chalcogenide|cycleformer|cyclicUnsaturableHydrocarbon|dedicatedFunctionalReplacementPrefix|endInAn|endInIc|endInIne|epoxyLike|glycolOrHalohydrin|groupStem|halideOrPseudoHalide|hantzschWidman|heteroStem|fusionRing|simpleGroup|multiRadicalSubstituent|noAcyl|none|ousIcAtom|oxidoLike|perhalogeno|phane|phospho|ring|saltComponent|simpleSubstituent|substituent|systematicCarbohydrateStemAldose|systematicCarbohydrateStemKetose|terminal|ylForAcyl|ylForNothing|ylForYl) #IMPLIED
                    symbol CDATA #REQUIRED
                    ignoreWhenWritingXML (yes) #IMPLIED>
<!-- tagname == the name of the XML element that tokens in this file will be translated to
type == the type attribute on the XML element (for example indicates that a group is an aminoAcid)
subType == the subType attribute on the XML element (gives additional information about what exactly the tokens represent)
symbol == the one-letter code for the token, used by the grammar in regexes.xml 
ignoreWhenWritingXML == Tells the parser not to form an XML element out of these tokens. That means that these token are only syntactic and contain no useful information and are not useful after parsing has completed-->

<!ELEMENT token (#PCDATA)>
<!ATTLIST token value CDATA #REQUIRED
        acceptsAdditiveBonds CDATA #IMPLIED
        addBond CDATA #IMPLIED
        addGroup CDATA #IMPLIED
        addHeteroAtom CDATA #IMPLIED
        additionalValue CDATA #IMPLIED
        alphaBetaClockWiseAtomOrdering CDATA #IMPLIED
        commonOxidationStatesAndMax CDATA #IMPLIED
        defaultInID CDATA #IMPLIED
        defaultInLocant CDATA #IMPLIED
        frontLocantsExpected CDATA #IMPLIED
        functionalIDs CDATA #IMPLIED
        fusedRingNumbering CDATA #IMPLIED
        homology CDATA #IMPLIED
        iminoLike CDATA #IMPLIED
        labels CDATA #IMPLIED
        locant CDATA #IMPLIED
        naturalEntIsOpposite CDATA #IMPLIED
        outIDs CDATA #IMPLIED
        suffixAppliesTo CDATA #IMPLIED
        suffixAppliesToByDefault CDATA #IMPLIED
        usableAsAJoiner CDATA #IMPLIED
        stereoGroup CDATA #IMPLIED
>
<!--
  (the #PCDATA inside the tag) = the string to match
  value == Meaning depends on the name of the element e.g. SMILES for group, value of multipler for multiplier etc.

  acceptsAdditiveBonds == yes or absent. If present indicates that substituents (single radicals) will form additive bonds to this group when it has no hydrogen
  addBond == List of the following format: orderOfBond space ("id"|"locant"|"defaultId"|"defaultLocant") space (id|locant). If multiple bonds are to be added separate by semicolons e.g. "2 defaultLocant 1;3 defaultLocant 3". Use "locant" if name is unambiguous even when locants are not provided. MUST be used in conjunction with the frontLocantsExpected attribute
  addGroup == List of the following format: SMILESofGroupToBeAdded space ("id"|"locant"|"defaultId"|"defaultLocant") space (id|locant) [space locantLabel]. If multiple groups are to be added separate by semicolons e.g. "=O defaultLocant 9;=O defaultLocant 10" to add two double bonded oxygens, one by default at locant 9 and the other by default at locant 10. Use "locant" if name is unambiguous even when locants are not provided. MUST be used in conjunction with the frontLocantsExpected attribute
  addHeteroAtom == list of the following format: elementOfAtom space ("id"|"locant"|"defaultId"|"defaultLocant") space (id|locant). If multiple heteroatoms are to be added separate by semicolons e.g. "N defaultLocant 1;S defaultLocant 3". Use "locant" if name is unambiguous even when locants are not provided. MUST be used in conjunction with the frontLocantsExpected attribute
  additionalValue == Another value that the token takes. Currently only used for suffixes that mean the addition of two discrete suffixes
  alphaBetaClockWiseAtomOrdering == Listed in a clockwise order, the locants of the atoms that define a pseudo 2D plane for alpha/beta stereochemistry.
  commonOxidationStatesAndMax == For elements, the typical oxidation states (comma separated) then a colon and the maximum oxidation station. e.g. for iron "2,3:6" as 2 and 3 are typical. 6 is possible but atypical.
  defaultInID == The ID of the atom which by default an incoming fragment should connect to. ID is relative to this particular fragment (first atom =1)
  defaultInLocant == The locant of the atom which by default an incoming fragment should connect to. Typically used on groups
  frontLocantsExpected == Comma separated list of locants indicating what locants are expected in front of this group. If one of these locants is found it will preferentially be assigned to the suffix of the group. The group should correspond to a retained name. (codified in P-29.6 of IUPAC 2004 rules)
  functionalIDs == Comma separated IDs of locations which are functionalIDs on a group. IDs are relative to this particular fragment (first atom =1). Functional IDs are used in ester formation.
  fusedRingNumbering == The numbering to use for a ring when used in a fused ring system. Same syntax as labels attribute. It is only necessary where the ring has non-standard numbering that does not proceed regularly around the edge of the fused ring system c.f. purine
  homology == Semi-colon delimited list of labels for * atoms, used for when * atoms represent generic groups (homology groups) e.g. Alkyl
  iminoLike == yes or absent. If present indicates that the substituent can either be -X- or X= or even -X=. It changes some behaviour to encourage substitutive bonding rather than additive bonds where this substituent is involved. This attribute is mostly ignored when doing polymers for which imino is always -N-
  labels == Slash delimited list of locants. List must be the same length as number of atoms. Multiple locants can be given to an atom by comma delimiting them
  locant == Used for an/ane to prevent a locant being given
  naturalEntIsOpposite == yes or absent. Indicates that this trivial name has the opposite D/L stereochemistry to others in its class i.e. L- for carbohydrates or D- for amino acids
  outIDs == Comma separated IDs of locations of radicals on a substituent. Typically used on substituents to create multivalent substituents. IDs are relative to this particular fragment (first atom = 1)
  suffixAppliesTo == comma separated IDs indicating where the suffix following a group should be applied. Currently used to direct the formation of trivial di-acids. IDs are relative to this particular fragment first atom = 1)
  suffixAppliesToByDefault == same as suffixAppliesTo but can be overridden by given locants
  usableAsAJoiner == yes or absent. Can the substituent be implicitly bracketed to a previous substitutent e.g. methylaminobenzene becomes (methylamino)benzene as amino has this attribute
  stereoGroup == stereo group racemic/relative indication
  -->

=== dan2097/opsin/core/src/main/resources/uk/ac/cam/ch/wwmm/opsin/resources/miscTokens.xml
<!DOCTYPE tokenLists SYSTEM "tokenLists.dtd">
<!-- See the DTD for more details -->
<tokenLists>
  <tokenList tagname="hydrocarbonFusedRingSystem" symbol="V"><!--the a is part of the multiplier and the e is assumed to be optional -->
    <token value="polyacene">cen</token>
    <token value="polyalene">len</token>
    <token value="polyaphene">phen</token><!--ambiguity between this and multiplier phenyl e.g. hexaphenylbenzene is resolved in the ComponentGenerator generally in favour of phenyl-->
    <token value="polyphenylene">phenylen</token>
    <token value="polynaphthylene">naphthylen</token>
    <token value="polyhelicene">helicen</token>
  </tokenList>
  
  <tokenList tagname="cyclo" symbol="C">
    <token value="cyclo">cyclo</token>
    <token value="cyclo">cyclo-</token>
  </tokenList>

  <tokenList tagname="hydro" symbol="y">
    <token value="dehydro">dehydro</token>
    <token value="hydro">hydro</token>
  </tokenList>
  <tokenList tagname="hydro" symbol="ú">
    <token value="perhydro">perhydro</token>
  </tokenList>

  <tokenList tagname="stereoChemistry" type="cisOrTrans" symbol="t">
    <token value="cis">cis</token>
    <token value="trans">trans</token>
  </tokenList>

  <tokenList tagname="ine" symbol="î"><!--used for amino acids-->
    <token value="ine">ine</token>
    <token value="ine">in</token>
  </tokenList>

  <tokenList tagname="group" type="substituent" subType="multiRadicalSubstituent" symbol="ó"><!--chalcogen replacement terms-->
    <token value="S" labels="none" outIDs="1,1" valType="SMILES" usableAsAJoiner="yes" acceptsAdditiveBonds="yes">thio</token>
    <token value="[SeH2]" labels="none" outIDs="1,1" valType="SMILES" usableAsAJoiner="yes" acceptsAdditiveBonds="yes">seleno</token>
    <token value="[TeH2]" labels="none" outIDs="1,1" valType="SMILES" usableAsAJoiner="yes" acceptsAdditiveBonds="yes">telluro</token>
  </tokenList>

  <tokenList tagname="suffix" type="root" symbol="Ñ">
    <token value="amine">ylamine</token>
  </tokenList>

  <tokenList tagname="polyCyclicSpiro" symbol="º">
    <token value="spirobi">spirobi</token>
    <token value="spirobi">spirobi-</token>
    <token value="spiroter">spiroter</token>
    <token value="spiroter">spiroter-</token>
  </tokenList>

  <tokenList tagname="polyCyclicSpiro" symbol="⌐">
    <token value="spiro">spiro</token>
    <token value="spiro">spiro-</token>
  </tokenList>

  <tokenList tagname="polyCyclicSpiro" symbol="╝">
    <token value="spiroOldMethod">spiro</token>
    <token value="spiroOldMethod">spiro-</token>
  </tokenList>

  <tokenList tagname="dlStereochemistry" symbol="╛">
    <token value="d">d-</token>
    <token value="l">l-</token>
    <token value="dl">dl-</token>
<!--used to distinguish amino acid D/L from carbohydrate D/L if desired-->
    <token value="ds">ds-</token>
    <token value="dg">dg-</token>
    <token value="ls">ls-</token>
    <token value="lg">lg-</token>
  </tokenList>

<!--As a purely non-detachable prefixe-->
	<tokenList tagname="subtractivePrefix" symbol="┐">
		<token value="O">deoxy</token>
		<token value="O">desoxy</token><!--older variant spelling-->
	</tokenList>

<!--As a detachable prefix (which could itself have non-detachable prefixes in the case where it is being treated as a non-detachable prefix)-->
	<tokenList tagname="subtractivePrefix" symbol="x">
		<token value="O">deoxy</token>
		<token value="O">desoxy</token><!--older variant spelling-->
	</tokenList>
</tokenLists>

=== dan2097/opsin/opsin-core/src/main/resources/uk/ac/cam/ch/wwmm/opsin/resources/hwHeteroAtoms.xml
<!DOCTYPE tokenLists SYSTEM "tokenLists.dtd">
<!-- See the DTD for more details -->
<tokenLists>
  <!--For convenience in order of priority-->
  <tokenList tagname="heteroatom" symbol="D"><!--complete set including 2004 recommendations -->
    <token value="F" valType="SMILES">fluora</token>
    <token value="Cl" valType="SMILES">chlora</token>
    <token value="Br" valType="SMILES">broma</token>
    <token value="I" valType="SMILES">ioda</token>
    <token value="O" valType="SMILES">oxa</token>
    <token value="S" valType="SMILES">thia</token>
    <token value="[Se]" valType="SMILES">selena</token>
    <token value="[Te]" valType="SMILES">tellura</token>
    <token value="N" valType="SMILES">aza</token>
    <token value="P" valType="SMILES">phospha</token>
    <token value="[As]" valType="SMILES">arsa</token>
    <token value="[Sb]" valType="SMILES">stiba</token>
    <token value="[Bi]" valType="SMILES">bisma</token>
    <token value="[Si]" valType="SMILES">sila</token>
    <token value="[Ge]" valType="SMILES">germa</token>
    <token value="[Sn]" valType="SMILES">stanna</token>
    <token value="[Pb]" valType="SMILES">plumba</token>
    <token value="B" valType="SMILES">bora</token>
    <token value="[Al]" valType="SMILES">aluma</token>
    <token value="[Ga]" valType="SMILES">galla</token>
    <token value="[In]" valType="SMILES">indiga</token>
    <token value="[Tl]" valType="SMILES">thalla</token>
    <token value="[Hg]" valType="SMILES">mercura</token>

    <token value="F" valType="SMILES">fluor</token>
    <token value="Cl" valType="SMILES">chlor</token>
    <token value="Br" valType="SMILES">brom</token>
    <token value="I" valType="SMILES">iod</token>
    <token value="O" valType="SMILES">ox</token>
    <token value="S" valType="SMILES">thi</token>
    <token value="[Se]" valType="SMILES">selen</token>
    <token value="[Te]" valType="SMILES">tellur</token>
    <token value="N" valType="SMILES">az</token>
    <token value="P" valType="SMILES">phosph</token>
    <token value="[As]" valType="SMILES">ars</token>
    <token value="[Sb]" valType="SMILES">stib</token>
    <token value="[Bi]" valType="SMILES">bism</token>
    <token value="[Si]" valType="SMILES">sil</token>
    <token value="[Ge]" valType="SMILES">germ</token>
    <token value="[Sn]" valType="SMILES">stann</token>
    <token value="[Pb]" valType="SMILES">plumb</token>
    <token value="B" valType="SMILES">bor</token>
    <token value="[Al]" valType="SMILES">alum</token>
    <token value="[Ga]" valType="SMILES">gall</token>
    <token value="[In]" valType="SMILES">indig</token>
    <token value="[Tl]" valType="SMILES">thall</token>
    <token value="[Hg]" valType="SMILES">mercur</token>

    <token value="P" valType="SMILES">phosphor</token>
    <token value="[As]" valType="SMILES">arsen</token>
    <token value="[Sb]" valType="SMILES">antimon</token>
  </tokenList>

  <tokenList tagname="heteroatom" symbol="J"><!--hetero atoms that are compatable with an ine HWsuffix-->
    <token value="O" valType="SMILES">oxa</token>
    <token value="S" valType="SMILES">thia</token>
    <token value="[Se]" valType="SMILES">selena</token>
    <token value="[Te]" valType="SMILES">tellura</token>
    <token value="N" valType="SMILES">aza</token>
    <token value="[Bi]" valType="SMILES">bisma</token>
    <token value="[Si]" valType="SMILES">sila</token>
    <token value="[Ge]" valType="SMILES">germa</token>
    <token value="[Sn]" valType="SMILES">stanna</token>
    <token value="[Pb]" valType="SMILES">plumba</token>
    <token value="[Hg]" valType="SMILES">mercura</token>

    <token value="O" valType="SMILES">ox</token>
    <token value="S" valType="SMILES">thi</token>
    <token value="[Se]" valType="SMILES">selen</token>
    <token value="[Te]" valType="SMILES">tellur</token>
    <token value="N" valType="SMILES">az</token>
    <token value="[Bi]" valType="SMILES">bism</token>
    <token value="[Si]" valType="SMILES">sil</token>
    <token value="[Ge]" valType="SMILES">germ</token>
    <token value="[Sn]" valType="SMILES">stann</token>
    <token value="[Pb]" valType="SMILES">plumb</token>
    <token value="[Hg]" valType="SMILES">mercur</token>

    <token value="P" valType="SMILES">phosphor</token>
    <token value="[As]" valType="SMILES">arsen</token>
    <token value="[Sb]" valType="SMILES">antimon</token>
  </tokenList>

  <tokenList tagname="heteroatom" symbol="j"><!--hetero atoms that are compatable with an ane HWsuffix-->
    <token value="O" valType="SMILES">oxa</token>
    <token value="S" valType="SMILES">thia</token>
    <token value="[Se]" valType="SMILES">selena</token>
    <token value="[Te]" valType="SMILES">tellura</token>
    <token value="[Bi]" valType="SMILES">bisma</token>
    <token value="[Hg]" valType="SMILES">mercura</token>

    <token value="O" valType="SMILES">ox</token>
    <token value="S" valType="SMILES">thi</token>
    <token value="[Se]" valType="SMILES">selen</token>
    <token value="[Te]" valType="SMILES">tellur</token>
    <token value="[Bi]" valType="SMILES">bism</token>
    <token value="[Hg]" valType="SMILES">mercur</token>

    <token value="[As]" valType="SMILES">arsen</token>
  </tokenList>
</tokenLists>

=== dan2097/opsin/core/src/main/resources/uk/ac/cam/ch/wwmm/opsin/resources/functionalTerms.xml
<!DOCTYPE tokenLists SYSTEM "tokenLists.dtd">
<!-- See the DTD for more details -->
<tokenLists>
<!--functional classes typically have hard coded rules in the StructureBuilder detailing their behaviour-->
  <tokenList tagname="functionalClass" type="functionalClass" symbol="æ">
    <token value="acid">acid</token>
    <token value="ester">ester</token>
    <token value="glycol">glycol</token>
  </tokenList>

  <tokenList tagname="group" type="functionalClass" subType="functionalClassGroup" symbol="Æ">
<!--The atom that replaces the carbonyl oxygen is the last atom in the SMILES so that the first is where unlocanted substitution occurs)-->
    <token value="ON" labels="none" valType="SMILES">oxime</token>
    <token value="NN" labels="none" valType="SMILES">hydrazone</token>
    <token value="NC(=O)NN" labels="4/3//2/1" valType="SMILES">semicarbazone</token>
    <token value="NC(=S)NN" labels="4/3//2/1" valType="SMILES">thiosemicarbazone</token>
    <token value="NC(=[Se])NN" labels="4/3//2/1" valType="SMILES">selenosemicarbazone</token>
    <token value="NC(=[Te])NN" labels="4/3//2/1" valType="SMILES">tellurosemicarbazone</token>
    <token value="N" labels="none" valType="SMILES">imide</token>

    <token value="O" labels="none" valType="SMILES">oxide</token>
  </tokenList>

  <tokenList tagname="group" type="functionalClass" subType="anhydride" symbol="Ü">
    <token value="O" labels="none" valType="SMILES">anhydride</token>
    <token value="S" labels="none" valType="SMILES">thioanhydride</token>
    <token value="[Se]" labels="none" valType="SMILES">selenoanhydride</token>
    <token value="[Te]" labels="none" valType="SMILES">telluroanhydride</token>
    <token value="OO" labels="none" valType="SMILES">peroxyanhydride</token>
    <token value="SS" labels="none" valType="SMILES">dithioperoxyanhydride</token>
    <token value="[Se][Se]" labels="none" valType="SMILES">diselenoperoxyanhydride</token>
    <token value="[Te][Te]" labels="none" valType="SMILES">ditelluroperoxyanhydride</token>
  </tokenList>

  <tokenList tagname="functionalModifier" type="functionalModifier" symbol="ù">
    <token value="oligo">oligo</token>
    <token value="poly">poly</token>
  </tokenList>

<!--The functional groups simply involve connecting said group to a radical on the provided group
The standalone functionalgroups are alternatively valid as groups in their own right
For these groups the charge on the first atom will be increased by 1 if they are used as a functional group-->
  <tokenList tagname="functionalGroup" type="monoValentGroup" symbol="ô">
    <token value="O" labels="none" valType="SMILES">alcohol</token>
    <token value="[Se]" labels="none" valType="SMILES">selenol</token>
    <token value="S" labels="none" valType="SMILES">thiol</token>
  </tokenList>

  <tokenList tagname="functionalGroup" type="diValentGroup" symbol="ö">
    <token value="[Se][Se]-" labels="none" valType="SMILES">diselenide</token>
    <token value="SS-" labels="none" valType="SMILES">disulfide</token>
    <token value="[Te][Te]-" labels="none" valType="SMILES">ditelluride</token>
    <token value="O" labels="none" valType="SMILES">ether</token>
    <token value="C=O" labels="none" valType="SMILES">ketone</token>
    <token value="O" labels="none" valType="SMILES">oxide</token>
    <token value="OO-" labels="none" valType="SMILES">peroxide</token>
    <token value="[Se]" labels="none" valType="SMILES">selenide</token>
    <token value="[Se](=O)=O" labels="none" valType="SMILES">selenone</token>
    <token value="[Se]=O" labels="none" valType="SMILES">selenoxide</token>
    <token value="C=[Se]" labels="none" valType="SMILES">selone</token>
    <token value="[Se]=O" labels="none" valType="SMILES">selenoketone</token>
    <token value="S" labels="none" valType="SMILES">sulfide</token>
    <token value="S(=O)=O" labels="none" valType="SMILES">sulfone</token>
    <token value="S=O" labels="none" valType="SMILES">sulfoxide</token>
    <token value="[Te]" labels="none" valType="SMILES">telluride</token>
    <token value="[Te]=O" labels="none" valType="SMILES">telluroketone</token>
    <token value="[Te](=O)=O" labels="none" valType="SMILES">tellurone</token>
    <token value="[Te]=O" labels="none" valType="SMILES">telluroxide</token>
    <token value="S=O" labels="none" valType="SMILES">thioketone</token>
  </tokenList>

  <tokenList tagname="functionalGroup" type="monoValentStandaloneGroup" symbol="ò">
    <token value="[N-]=[N+]=[N-]" labels="none" valType="SMILES">azide</token>
    <token value="[Br-]" labels="none" valType="SMILES">bromide</token>
    <token value="[Cl-]" labels="none" valType="SMILES">chloride</token>
    <token value="[O-]C#N" labels="none" valType="SMILES">cyanate</token>
    <token value="[C-]#N" labels="none" valType="SMILES">cyanide</token>
    <token value="[F-]" labels="none" valType="SMILES">fluoride</token>
    <token value="[O-][N+]#[C-]" labels="none" valType="SMILES">fulminate</token>
    <token value="[O-]O" labels="none" valType="SMILES">hydroperoxide</token>
    <token value="[I-]" labels="none" valType="SMILES">iodide</token>
    <token value="[N-]=C=O" labels="none" valType="SMILES">isocyanate</token>
    <token value="N#[C-]" labels="none" valType="SMILES">isocyanide</token>
    <token value="[N-]=C=[Se]" labels="none" valType="SMILES">isoselenocyanate</token>
    <token value="[N-]=C=[Te]" labels="none" valType="SMILES">isotellurocyanate</token>
    <token value="[N-]=C=S" labels="none" valType="SMILES">isothiocyanate</token>
    <token value="[Se-]C#N" labels="none" valType="SMILES">selenocyanate</token>
    <token value="[Te-]C#N" labels="none" valType="SMILES">tellurocyanate</token>
    <token value="[S-]C#N" labels="none" valType="SMILES">thiocyanate</token>
  </tokenList>

</tokenLists>

=== dan2097/opsin/core/src/main/resources/uk/ac/cam/ch/wwmm/opsin/resources/cyclicUnsaturableHydrocarbon.xml
<!DOCTYPE tokenLists SYSTEM "tokenLists.dtd">
<!-- See the DTD for more details -->
<tokenLists>
  <tokenList tagname="group" type="ring" subType="cyclicUnsaturableHydrocarbon" symbol="A">
    <token value="C12CC3CC4CC5C1.C24.C35" valType="SMILES" frontLocantsExpected="1,2">adamant</token>
    <token value="C12C3C4C11.C35C2C1C45" valType="SMILES">cub</token>
    <token value="C12C3C4C1C4C32" valType="SMILES">prism</token>
  </tokenList>

  <tokenList tagname="group" type="ring" subType="cyclicUnsaturableHydrocarbon" symbol="A">
    <!-- terpenes-->
    <token value="C123CCC4CC1.C24(C)C.C3" valType="SMILES">born</token>
      <token value="C123CCC4CC1.C24(C)C.C3" valType="SMILES">camph</token>
      <token value="C123CCC4CC1.C24(C)C.C3" valType="SMILES">bornyl</token>
    <token value="C12CC3CCC1C2(C)C.C3" valType="SMILES">car</token>
    <!--it's quicker to write out all forms of this than create a special case for menthane to allow things like 1-p-menthene-->
    <token value="C12CCC3CC1.C2.C3(C)C" valType="SMILES" defaultInLocant="3">menth</token>
    <token value="C12CCC3CC1.C2.C3(C)C" valType="SMILES" defaultInLocant="3">p-menth</token>
    <token value="C12CCC3CC1.C2.C3(C)C" valType="SMILES" defaultInLocant="3">para-menth</token>
    <token value="C12CC3CCC1.C2.C3(C)C" valType="SMILES">m-menth</token>
    <token value="C12CC3CCC1.C2.C3(C)C" valType="SMILES">meta-menth</token>
    <token value="C12C3CCCC1.C2.C3(C)C" valType="SMILES">o-menth</token>
    <token value="C12C3CCCC1.C2.C3(C)C" valType="SMILES">ortho-menth</token>
    <token value="C12CCC(CC2)C1" valType="SMILES">norborn</token>
      <token value="C12CCC(CC2)C1" valType="SMILES">norcamph</token>
      <token value="C12CCC(CC2)C1" valType="SMILES">norbornyl</token>
    <token value="C12CCCCC2C1" valType="SMILES">norcar</token>
    <token value="C12CCCC(C2)C1" valType="SMILES">norpin</token>
    <token value="C12C3CCC4C156.C24.C5.C6.C3" valType="SMILES">pin</token>
    <token value="C123CCC4C1C2.C3(C)C.C4" valType="SMILES">thuj</token>
  </tokenList>
</tokenLists>
